version: 2.1

step_install_nvm: &step_install_nvm
  run:
    name: "Install nvm for machine"
    command: |
      set +e
      export NVM_DIR="/opt/circleci/.nvm"
      [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
      nvm install v12.16.0
      nvm alias default v12.16.0
      echo 'export NVM_DIR="/opt/circleci/.nvm"' >> $BASH_ENV
      echo "[ -s \"$NVM_DIR/nvm.sh\" ] && . \"$NVM_DIR/nvm.sh\"" >> $BASH_ENV
jobs:
  unit:
    machine: true
    steps:
      - checkout
      - <<: *step_install_nvm
      - run: npm install -g yarn;
      - run: yarn
      - run: npm test
workflows:
  version: 2
  build:
    jobs:
      - unit
